### ISSUE TITLE
Jenkins jobs are not being triggered

### ISSUE THREAD

**Issue by yakimant** [codex-storage/codex.storage#35]
Both jobs are not being triggered:
- https://ci.infra.status.im/job/website/job/dev.codex.storage
- https://ci.infra.status.im/job/website/job/codex.storage

Probably due to the move `acid-info/codex.storage` to `codex-storage/codex.storage`

I tried the following:
1. Add `status-im-auto` as Admin to the repo
2. Change configuration from `acid-info/codex.storage` to `codex-storage/codex.storage`
3. "Re-register hooks for all jobs" in GitHub plugin advanced settings: https://ci.infra.status.im/manage/configure

It still shows acid in the logs:
```
GitHub webhooks activated for job website/codex.storage with [GitHubRepositoryName[host=github.com,username=acid-info,repository=codex.storage]] (events: [PUSH])
```

**Comment by yakimant** [comment]
After removing the webhook from GitHub and "" the following message is shown in Job configuration:
> The webhook for repo acid-info/codex.storage on github.com failed to be registered or was removed. More info can be found on the global configuration page. This message will be dismissed if Jenkins receives a PING event from repo webhook or if you add the repo to the ignore list in the global configuration.
Smth got wrong, will recreate dev job.

**Comment by yakimant** [comment]
Copied job has the following in the logs:
```
GitHub webhooks activated for job website/dev.codex.storage new with [] (events: [PUSH])
```

**Comment by yakimant** [comment]
Ok, the following helped:

1. Remove GitHub webhook in the repo
2. Created configurations from scratch (with new repo URL)
3. Run job manually in each
4. "Re-register hooks for all jobs"

Webhook was registered and now I see proper log line:
```
GitHub webhooks activated for job website/dev.codex.storage with [GitHubRepositoryName[host=github.com,username=codex-storage,repository=codex.storage]] (events: [PUSH])
```

Probably related issue:
https://issues.jenkins.io/browse/JENKINS-37217

Looks like Jenkins doesn't really support repo move.
You need to recreate a configuration from scratch.

**Comment by yakimant** [comment]
Fixed and tested.
@jeangovil, feel free to reopen if you find any issues.
@jakubgs, please review, when you are back

**Comment by jakubgs** [comment]
Yes, running `Re-register hooks for all jobs` often helps, but in some rare cases a job has to be recreated.
